services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    links:
      - backend
    ports:
      - "${WEB_PORT}:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  postgres_data: