version: "3.8"

services:
  backend:
    build: .
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: